services:
  app:
    image: ${DOCKER_IMAGE:-backupmailer}:${IMAGE_TAG:-latest}
    container_name: backupmailer-${ENV_SUFFIX:-dev}
    restart: always
    env_file:
      - .env
    volumes:
      - ${BACKUP_PATH}:${BACKUP_PATH}
      - ./logs:/app/logs
